### ISSUE TITLE
PR to own repo

### ISSUE THREAD

**Issue by M-Zuber** [librariesio/firstprbot#16]
Currently this gets fired even if the user makes a PR to a repo they own.
If this is not the desired functionality, the search url needs to be updated.
In order to fix this, [this line](https://github.com/librariesio/firstprbot/blob/master/index.js#L19) should be updated to:

``` js
var searchURL = 'https://api.github.com/search/issues?q=type:pr+author:"'+login+'"+-user:"'+login+'"&sort=created&order=asc&per_page=1&access_token='+process.env.GITHUB_TOKEN
```

**Comment by andrew** [comment]
Yeah I forgot about that, fancy sending a pr similar to https://github.com/andrew/first-pr/pull/23?

**Comment by M-Zuber** [comment]
Updated w/ instructions.
What else needs to be added to make it first-pr friendly?

**Comment by andrew** [comment]
Labelled it up 👍
